[build]
  publish = "WomosiGo/WomosiGo-app/dist"
  command = "cd WomosiGo/WomosiGo-app && npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.herokuapp.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
